---
title: "My Publish"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

* [Hou SP, Fang AH, Chen QF, Huang YM, Chen OJ, Cheng LN. Termination of second-trimester pregnancy by mifepristone combined with misoprostol versus intra-amniotic injection of ethacridine lactate (Rivanol®): a systematic review of Chinese trials. Contraception. 2011 Sep;84(3):214-23](https://www.ncbi.nlm.nih.gov/pubmed/21843683)

* [2.	Chen QJ, Hou SP, Meads C, Huang YM, Hong QQ, Zhu HP, Cheng LN; EBM-CONNECT Collaboration. Mifepristone in combination with prostaglandins for termination of 10-16 weeks' gestation: a systematic review. Eur J Obstet Gynecol Reprod Biol. 2011 Dec;159(2):247-54](https://www.ncbi.nlm.nih.gov/pubmed/21741747)

* [3.	Huang YM, Merkatz R, Kang JZ, Roberts K, Hu XY, Di Donato F, Sitruk-Ware R, Cheng LN. Postpartum unintended pregnancy and contraception practice among rural-to-urban migrant women in Shanghai. Contraception. 2012 Dec;86(6):731-8](https://www.ncbi.nlm.nih.gov/pubmed/22703950)

* [4.	Huang Y, Merkatz R, Zhu H, Roberts K, Sitruk-Ware R, Cheng L; Perinatal/Postpartum Contraceptive Services Project for Migrant Women Study Group. The free perinatal/postpartum contraceptive services project for migrant women in Shanghai: effects on the incidence of unintended pregnancy. Contraception. 2014 Jun;89(6):521-7](https://www.ncbi.nlm.nih.gov/pubmed/24792146)