---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(ggplot2)

set.seed(1)
data("rest_inspec")

```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}
##According the number of restaurant of Manhattan to
##filter top 10 ZIP code
top10_zipcode <- rest_inspec %>% 
  filter(
    boro == "MANHATTAN",
    is.na(score) != TRUE
  ) %>% 
  count(zipcode, sort = TRUE) %>% 
  top_n(10) %>% 
  select(zipcode) %>% 
  mutate(zipcode = as.character(zipcode))

##box plot
rest_inspec %>% 
  filter(
    is.na(score) != TRUE
  ) %>% 
  mutate(zipcode = as.character(zipcode)) %>% 
  inner_join(x = ., y = top10_zipcode, by = "zipcode") %>% 
  mutate(zipcode = fct_reorder(zipcode, score)) %>% 
  plot_ly(x = ~zipcode, y = ~score, color = ~zipcode, type = "box") %>% 
  layout(
    title = list(text = "Fig 1. The boxplots of restraurant scores by top 10 zip code area 
with most restraurants in Manhattan ", x = 0.0, titlefont=list(size=20)),
    legend = list(y = 0.5),
    xaxis = list(title = "ZIP Code", titlefont=list(size=15)),
    yaxis = list(title = "Score", titlefont=list(size=15))
    ) 

```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B

```{r}
##the number of grades of Donuts in five boro of NYC
rest_inspec %>% 
  filter(
    str_detect(cuisine_description, "[Dd][Oo][Nn][Uu][Tt][Ss]"),
    is.na(grade) == FALSE
  ) %>% 
  group_by(boro, grade) %>% 
  summarize(
    n = n()
  ) %>% 
  pivot_wider(
    names_from = "grade",
    values_from = "n"
  ) %>% 
  plot_ly(
    x = ~boro,
    y = ~A,
    type = "bar",
    name = "Grade A"
  ) %>% 
  add_trace(
    y = ~B,
    name = "Grade B"
  ) %>% 
  add_trace(
    y = ~C,
    name = "Grade C"
  ) %>% 
  add_trace(
    y = ~P,
    name = "Grade P"
  ) %>% 
  add_trace(
    y = ~Z,
    name = "Grade Z"
  ) %>% 
  layout(
    title = list(text = "Fig 2. The Donuts restaurants of grade in five borough of NYC ", x = 0.0, titlefont=list(size=20)),
    legend = list(y = 0.5),
    xaxis = list(title = "Borough", titlefont=list(size=15)),
    yaxis = list(title = "Count", titlefont=list(size=15)),
    barmode = "stack"
  )

```

### Chart C

```{r}
##scatter
fig3_score_trend <- rest_inspec %>% 
  filter(
    is.na(grade) == FALSE,
    boro == "MANHATTAN"
  ) %>%
  select(score, grade_date, boro) %>% 
  mutate(
    year = substring(grade_date, 1, 4),
    grade_date = substring(grade_date, 6, 7)
  ) %>% 
  filter(
    is.na(year) == FALSE,
    year %in% c("2015", "2016", "2017")
  ) 

ggplotly(
  ggplot(fig3_score_trend, aes(x = grade_date, y = score, group = year)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~year, nrow  = 1) +
  labs(
    title = "Fig 3. Trends of restaurant score in Manhattan from 2015 to 2017",
    x = "Month of year",
    y = "Score"
  ) +
  theme(
    axis.text = element_text(size=6),
    axis.title.x.bottom = element_text(color="black", 
                           size=8), 
    axis.title.y.left = element_text(color="black", 
                           size=8),
    title = element_text(color="black", 
                           size=12)
  ) 
  ) 
```

